"""Generate LaTeX macros for Paper B from CSV data files.

Single source of truth: all numbers in the paper come from this script.
Regenerate with: python Code/generate_paper_b_macros.py
"""
import csv, math, os
from pathlib import Path
from collections import Counter

DATA_DIR = Path(__file__).resolve().parent.parent
OUT_DIR = DATA_DIR / "Documentation" / "generated"
OUT_DIR.mkdir(parents=True, exist_ok=True)

def mean(xs): return sum(xs) / len(xs) if xs else 0
def median_val(xs):
    s = sorted(xs)
    n = len(s)
    if n == 0: return 0
    if n % 2 == 1: return s[n//2]
    return (s[n//2 - 1] + s[n//2]) / 2
def std(xs):
    m = mean(xs)
    return (sum((x-m)**2 for x in xs) / len(xs)) ** 0.5 if xs else 0
def corr(xs, ys):
    mx, my = mean(xs), mean(ys)
    sx, sy = std(xs), std(ys)
    if sx == 0 or sy == 0: return 0
    return sum((x-mx)*(y-my) for x,y in zip(xs,ys)) / (len(xs) * sx * sy)

def load_humans():
    rows = []
    with open(DATA_DIR / "Human_Scores.csv", newline="") as f:
        reader = csv.DictReader(f, skipinitialspace=True)
        for row in reader:
            try:
                score = float(row["Score"].strip())
                correct = int(row["Correct"].strip())
                rows.append({"score": score, "correct": correct})
            except (ValueError, KeyError):
                continue
    return rows

def load_ais():
    rows = []
    with open(DATA_DIR / "AI_Scores.csv", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row["AI"].strip()
            score_val = None
            for k, v in row.items():
                if "score" in k.strip().lower():
                    try: score_val = float(v.strip())
                    except: pass
                    break
            correct = None
            for k, v in row.items():
                if "correct" in k.strip().lower():
                    try: correct = int(v.strip())
                    except: pass
                    break
            rows.append({"name": name, "score": score_val, "correct": correct})
    return rows

def main():
    humans = load_humans()
    ais = load_ais()

    ai_initial = [a for a in ais if "combined" not in a["name"].lower()
                  and a["score"] is not None and a["correct"] is not None]
    ai_combined = [a for a in ais if "combined" in a["name"].lower()
                   and a["score"] is not None and a["correct"] is not None]

    h_scores = [h["score"] for h in humans]
    h_correct = [h["correct"] for h in humans]
    h_spc = [h["score"]/h["correct"] for h in humans if h["correct"] > 0]

    ai_scores = [a["score"] for a in ai_initial]
    ai_correct = [a["correct"] for a in ai_initial]
    ai_spc = [a["score"]/a["correct"] for a in ai_initial if a["correct"] > 0]

    m = []
    m.append("% Auto-generated macros for Paper B: AI vs Human Metacognition")
    m.append("% Source: Human_Scores.csv, AI_Scores.csv")
    m.append(f"% Generated by: Code/generate_paper_b_macros.py")
    m.append("")

    # Human stats
    m.append("% --- Human students ---")
    m.append(f"\\newcommand{{\\humanN}}{{{len(humans)}}}")
    m.append(f"\\newcommand{{\\humanScoreMean}}{{{mean(h_scores):.1f}}}")
    m.append(f"\\newcommand{{\\humanScoreMedian}}{{{median_val(h_scores):.1f}}}")
    m.append(f"\\newcommand{{\\humanScoreStd}}{{{std(h_scores):.1f}}}")
    m.append(f"\\newcommand{{\\humanScoreMin}}{{{min(h_scores):.1f}}}")
    m.append(f"\\newcommand{{\\humanScoreMax}}{{{max(h_scores):.1f}}}")
    m.append(f"\\newcommand{{\\humanCorrectMean}}{{{mean(h_correct):.1f}}}")
    m.append(f"\\newcommand{{\\humanCorrectMedian}}{{{median_val(h_correct):.0f}}}")
    m.append(f"\\newcommand{{\\humanAccuracy}}{{{mean(h_correct)/10*100:.0f}}}")
    m.append(f"\\newcommand{{\\humanScoreCorrectCorr}}{{{corr(h_scores, h_correct):.3f}}}")
    m.append(f"\\newcommand{{\\humanSPC}}{{{mean(h_spc):.2f}}}")

    n_neg = sum(1 for h in humans if h["score"] < 0)
    n_zero = sum(1 for h in humans if h["score"] == 0)
    m.append(f"\\newcommand{{\\humanNegScores}}{{{n_neg}}}")
    m.append(f"\\newcommand{{\\humanZeroScores}}{{{n_zero}}}")
    m.append(f"\\newcommand{{\\humanNegPct}}{{{n_neg/len(humans)*100:.0f}}}")

    # Per-correct-count stats
    for nc in [4, 6, 8, 10]:
        subset = [h for h in humans if h["correct"] == nc]
        if subset:
            avg = mean([h["score"] for h in subset])
            m.append(f"\\newcommand{{\\humanAvgScoreAt{nc}}}{{{avg:.1f}}}")
            m.append(f"\\newcommand{{\\humanCountAt{nc}}}{{{len(subset)}}}")

    m.append("")
    m.append("% --- AI models ---")
    m.append(f"\\newcommand{{\\aiNInitial}}{{{len(ai_initial)}}}")
    m.append(f"\\newcommand{{\\aiNCombined}}{{{len(ai_combined)}}}")
    m.append(f"\\newcommand{{\\aiScoreMean}}{{{mean(ai_scores):.1f}}}")
    m.append(f"\\newcommand{{\\aiCorrectMean}}{{{mean(ai_correct):.1f}}}")
    m.append(f"\\newcommand{{\\aiAccuracy}}{{{mean(ai_correct)/10*100:.0f}}}")
    m.append(f"\\newcommand{{\\aiSPC}}{{{mean(ai_spc):.2f}}}")

    # AI max-confidence count
    n_max_conf = sum(1 for a in ai_initial
                     if a["correct"] > 0
                     and abs(a["score"] - (a["correct"]*2 - (10-a["correct"])*2)) < 1.5)
    m.append(f"\\newcommand{{\\aiMaxConfCount}}{{{n_max_conf}}}")
    m.append(f"\\newcommand{{\\aiMaxConfPct}}{{{n_max_conf/len(ai_initial)*100:.0f}}}")

    # Avg penalty per wrong answer for AI
    penalties = []
    for a in ai_initial:
        n_wrong = 10 - a["correct"]
        if n_wrong > 0:
            penalties.append((a["score"] - a["correct"]*2.0) / n_wrong)
    if penalties:
        m.append(f"\\newcommand{{\\aiAvgPenalty}}{{{mean(penalties):.1f}}}")

    m.append("")
    m.append("% --- Comparison ---")
    m.append(f"\\newcommand{{\\spcGap}}{{{mean(ai_spc) - mean(h_spc):.2f}}}")
    m.append(f"\\newcommand{{\\accuracyGap}}{{{(mean(ai_correct) - mean(h_correct))/10*100:.0f}}}")
    m.append(f"\\newcommand{{\\nQuestions}}{{10}}")
    m.append(f"\\newcommand{{\\nConfLevels}}{{3}}")

    out_path = OUT_DIR / "paper_b_macros.tex"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(m))
    print(f"Wrote {out_path}")
    print(f"  {len([x for x in m if 'newcommand' in x])} macros generated")

if __name__ == "__main__":
    main()
