-- CBM LTI Plugin Schema
-- Supports both System 1 (Quiz Runner) and System 2 (Submission Validator)

-- ── Assignment Configuration (set by instructor via Deep Linking) ──

CREATE TABLE IF NOT EXISTS assignment_config (
  id TEXT PRIMARY KEY,
  course_id TEXT NOT NULL,
  assignment_id TEXT NOT NULL,

  -- Mode: 'quiz_runner' or 'submission_validator'
  tool_mode TEXT NOT NULL,

  -- Display name (shown to students)
  title TEXT NOT NULL DEFAULT 'CBM Assessment',

  -- Quiz Runner settings
  qti_json TEXT,                        -- Parsed QTI questions JSON (System 1)
  question_count INTEGER,               -- Number of questions in quiz

  -- Submission Validator settings
  timing_mode TEXT DEFAULT 'immediate', -- 'immediate', 'deadline', 'tutorial'
  deadline_hours INTEGER,               -- Hours after submission (deadline mode)
  mcq_count INTEGER DEFAULT 10,         -- Number of MCQs to generate
  oral_count INTEGER DEFAULT 3,         -- Number of oral questions to generate

  -- Shared scoring config
  scoring_model TEXT DEFAULT 'hlcc',    -- 'hlcc' or 'discrete_cbm'
  confidence_levels INTEGER DEFAULT 3,  -- 3 or 5
  max_grade_multiplier REAL DEFAULT 1.5,-- Max grade = multiplier * question_count

  -- LTI context
  line_item_url TEXT,                   -- For grade passback
  platform_id TEXT,

  created_by TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  UNIQUE(course_id, assignment_id)
);

-- ── Question Bank (shared across courses) ──

CREATE TABLE IF NOT EXISTS question_bank (
  id TEXT PRIMARY KEY,
  course_id TEXT,                        -- NULL = global
  question_text TEXT NOT NULL,
  question_type TEXT NOT NULL DEFAULT 'multiple_choice',
  options TEXT NOT NULL,                 -- JSON array of {id, text}
  correct_answer TEXT NOT NULL,          -- option id or text
  explanation TEXT,
  topic TEXT,
  subtopic TEXT,
  keywords TEXT,                         -- JSON array
  complexity_level INTEGER DEFAULT 5,    -- 1-10
  source TEXT DEFAULT 'imported',        -- 'imported', 'generated', 'manual'
  qti_identifier TEXT,                   -- Original QTI ID if imported
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_qb_course ON question_bank(course_id);
CREATE INDEX IF NOT EXISTS idx_qb_topic ON question_bank(topic);

-- ── Question Embeddings (for FAISS matching in System 2) ──

CREATE TABLE IF NOT EXISTS question_embeddings (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL,
  embedding_model TEXT NOT NULL DEFAULT 'all-MiniLM-L6-v2',
  embedding_vector BLOB NOT NULL,       -- Float32 array as binary
  text_used TEXT,                        -- The text that was embedded
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (question_id) REFERENCES question_bank(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_qe_question ON question_embeddings(question_id);
CREATE INDEX IF NOT EXISTS idx_qe_model ON question_embeddings(embedding_model);

-- ── Quiz Sessions (System 1: CBM Quiz Runner) ──

CREATE TABLE IF NOT EXISTS quiz_sessions (
  id TEXT PRIMARY KEY,
  assignment_config_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  student_name TEXT,
  course_id TEXT NOT NULL,

  -- Session state
  status TEXT DEFAULT 'active',         -- active, submitted, expired
  questions_json TEXT NOT NULL,         -- Questions shown to this student (with shuffled order)
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP,
  expires_at TIMESTAMP,

  -- Results
  raw_score REAL,
  max_possible REAL,                    -- 2 * question_count (HLCC max)
  normalized_score REAL,                -- Mapped to Canvas scale
  grade_submitted INTEGER DEFAULT 0,

  -- LTI context for grade passback
  lti_token_data TEXT,                  -- Serialized token for later passback

  FOREIGN KEY (assignment_config_id) REFERENCES assignment_config(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_qs_student ON quiz_sessions(student_id, assignment_config_id);

-- ── Submissions (System 2: PDF uploads) ──

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  assignment_config_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  student_name TEXT,
  course_id TEXT NOT NULL,

  -- File info
  original_filename TEXT NOT NULL,
  stored_path TEXT NOT NULL,
  file_size INTEGER,
  word_count INTEGER,

  -- Processing state
  status TEXT DEFAULT 'uploaded',       -- uploaded, analyzing, ready, completed, error
  error_message TEXT,
  processed_at TIMESTAMP,

  -- Content analysis
  chunk_count INTEGER,
  matched_question_count INTEGER,       -- Questions found in bank
  generated_question_count INTEGER,     -- Questions generated by LLM

  -- LTI context
  lti_token_data TEXT,

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (assignment_config_id) REFERENCES assignment_config(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sub_student ON submissions(student_id, assignment_config_id);

-- ── Assessment Questions (questions assigned to a specific session/submission) ──

CREATE TABLE IF NOT EXISTS assessment_questions (
  id TEXT PRIMARY KEY,
  -- Links to either quiz_session or submission
  quiz_session_id TEXT,
  submission_id TEXT,

  question_bank_id TEXT,                -- NULL if generated ad-hoc
  question_order INTEGER NOT NULL,

  -- Question content (denormalized for display)
  question_text TEXT NOT NULL,
  question_type TEXT NOT NULL DEFAULT 'multiple_choice',
  options TEXT NOT NULL,                 -- JSON array
  correct_answer TEXT NOT NULL,
  explanation TEXT,

  -- Metadata
  source TEXT DEFAULT 'bank',           -- 'bank', 'generated', 'oral'
  category TEXT DEFAULT 'standard',     -- 'standard', 'novel', 'oral'
  topic TEXT,
  is_oral INTEGER DEFAULT 0,            -- 1 = oral question (tutor-only)

  FOREIGN KEY (quiz_session_id) REFERENCES quiz_sessions(id) ON DELETE CASCADE,
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (question_bank_id) REFERENCES question_bank(id) ON DELETE SET NULL
);

-- ── Student Responses ──

CREATE TABLE IF NOT EXISTS student_responses (
  id TEXT PRIMARY KEY,
  assessment_question_id TEXT NOT NULL,
  student_id TEXT NOT NULL,

  -- Answer
  selected_answer TEXT NOT NULL,
  is_correct INTEGER NOT NULL,          -- 0 or 1
  confidence_level INTEGER NOT NULL,    -- 1-3 or 1-5

  -- CBM scoring
  cbm_score REAL NOT NULL,              -- Calculated score for this question
  time_spent_seconds INTEGER,

  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (assessment_question_id) REFERENCES assessment_questions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sr_student ON student_responses(student_id);
CREATE INDEX IF NOT EXISTS idx_sr_question ON student_responses(assessment_question_id);

-- ── Deferred Assessments (System 2 timing control) ──

CREATE TABLE IF NOT EXISTS deferred_assessments (
  id TEXT PRIMARY KEY,
  submission_id TEXT NOT NULL,
  student_id TEXT NOT NULL,
  course_id TEXT NOT NULL,

  -- Timing
  timing_mode TEXT NOT NULL,            -- 'immediate', 'deadline', 'tutorial'
  available_at TIMESTAMP,
  deadline_at TIMESTAMP,
  activated_by TEXT,                    -- Admin who activated (tutorial mode)
  activated_at TIMESTAMP,

  -- State
  status TEXT DEFAULT 'pending',        -- pending, available, in_progress, submitted, expired
  started_at TIMESTAMP,
  submitted_at TIMESTAMP,

  -- Results
  raw_score REAL,
  max_possible REAL,
  normalized_score REAL,
  grade_submitted INTEGER DEFAULT 0,

  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_da_student ON deferred_assessments(student_id, status);
CREATE INDEX IF NOT EXISTS idx_da_deadline ON deferred_assessments(deadline_at, status);

-- ── CBM Scoring Rules ──

CREATE TABLE IF NOT EXISTS cbm_scoring_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  confidence_level INTEGER NOT NULL,
  correct_score REAL NOT NULL,
  incorrect_score REAL NOT NULL,
  label TEXT NOT NULL,
  description TEXT
);

-- Default 3-level HLCC rules
INSERT OR IGNORE INTO cbm_scoring_rules (confidence_level, correct_score, incorrect_score, label, description)
VALUES
  (1, 1.0, 0.0, 'Low', 'Safe guess — no penalty if wrong'),
  (2, 1.5, -0.5, 'Medium', 'Moderate risk — small penalty if wrong'),
  (3, 2.0, -2.0, 'High', 'High reward — high penalty if wrong');
